spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_database
    username: root
    password: Lenkeran5566
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
